### ISSUE TITLE
Question Mark - does not work on mobile phone

### ISSUE THREAD

**Issue by jason-ziptrak** [andriimisiats/find-a-retailer#1]
The light grey question mark next to "Store" and "Products" did not work for my on my mobile phone. I could not click it. 

It works well on Firefox on PC browser.

**Comment by andriimisiats** [comment]
The question mark's tooltip appears, when user move mouse over this element. 
It is obvious that on the mobile phone user can only press this question mark. 
I will update add a click event to question mark tomorrow.

**Comment by jason-ziptrak** [comment]
Ok, thanks Andrey. So the "click event" will be updated to accept a mobile user pressing on the question mark, instead of hovering like a desktop user - yes?

**Comment by andriimisiats** [comment]
Yes. To see tooltip on PC, you have to move mouse over question mark.
On mobile, you have to click question mark. On the image below, you can look at result on IPhone 5.

![image](https://user-images.githubusercontent.com/26199758/38329125-8246ad94-3855-11e8-9d0a-7b412d2a169b.png)

Please, let me know, if result is not good.

**Comment by andriimisiats** [comment]
I tried to move new question mark functions, but it doesn't work on test hosting.
The same situation with Trade Hub. 

Everything works perfectly on my local server, on test hosting not. Try one more time tomorrow.

Best regards,
Andrey

**Comment by jason-ziptrak** [comment]
Hi Andrey, 

Using on my mobile phone, it does not appear to work. The question mark symbol is unresponsive to my finger touch.

**Comment by andriimisiats** [comment]
Hi Jason,
I fixed it. 
The problem was in ... Country Selector.
I fixed country selector and tooltip appears on phone. 
You never know what can happen.

**Comment by jason-ziptrak** [comment]
Hi Andrey, 

My testing this morning on a iPhone X shows that the tooltip question mark is still not responsive to a finger tough. Can you do a screen print and specify which phone you are using for testing?

**Comment by andriimisiats** [comment]
Hi Jason,

I tested one more time today on my phone (Samsung Galaxy Core Prime) and question mark looks good.
Also, I tested in Google Chrome on phones:
Galaxy S5, Pixel 2, Pixel 2 XL, IPhone 5/SE, 6, 7, 8/8 Plus, X, IPad.

Screenshot IPhone X:
![image](https://user-images.githubusercontent.com/26199758/38521536-a67d8938-3c4e-11e8-8d9a-7254befd7605.png)

My phone (Samsung Galaxy Core Prime): 
![photo_2018-04-09_23-37-44](https://user-images.githubusercontent.com/26199758/38521725-343542de-3c4f-11e8-8fa5-cba04e51b6e6.jpg)

**Comment by jason-ziptrak** [comment]
Hi Andrey, 

Thanks for this research. Marc has a windows phone and its working, we have confirmed. However its not working on an iphone X. It seems you may be using a browser to test all these different platforms. Unfortunately, I don't think this is an accurate way to understand the actual performance of these platforms. 

I'm not sure if you can do anything else to test on Apple Iphone Device in Safari? I think we can launch without this issue resolved, but would like you to continue to research. Thanks.

**Comment by andriimisiats** [comment]
Hi Jason,
Sorry for slow response. I found similar issue on IPhone 5.
Now, it seems everything is good (Screenshot Iphone 5):
![image](https://user-images.githubusercontent.com/26199758/38780411-58455fb8-40de-11e8-8263-5a9d93b07bc6.png)

Thank you.

**Comment by jason-ziptrak** [comment]
Hi Andrey, my testing has shown this is now working. Thank you. Item resolved.
